version: '3.8'

services:
  db:
    image: postgres:14
    container_name: ticketing_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: ticketing_web
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/ticketdb
      FLASK_ENV: development
    depends_on:
      - db

volumes:
  postgres_data:
